// Mocks generated by Mockito 5.4.4 from annotations
// in ricky_morty_list_char/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:ricky_morty_list_char/core/error/failure.dart' as _i6;
import 'package:ricky_morty_list_char/modules/home/domain/entities/character_entity.dart'
    as _i8;
import 'package:ricky_morty_list_char/modules/home/domain/entities/episode_entity.dart'
    as _i7;
import 'package:ricky_morty_list_char/modules/home/domain/repositories/rick_and_morty_repository.dart'
    as _i4;
import 'package:ricky_morty_list_char/modules/home/domain/usecases/load_characters_usecase.dart'
    as _i10;
import 'package:ricky_morty_list_char/modules/home/domain/usecases/load_episode_usecase.dart'
    as _i9;
import 'package:ricky_morty_list_char/modules/home/infra/datasource/local_datasource.dart'
    as _i13;
import 'package:ricky_morty_list_char/modules/home/infra/datasource/remote_datasource.dart'
    as _i11;
import 'package:ricky_morty_list_char/modules/home/infra/model/episode.dart'
    as _i3;
import 'package:ricky_morty_list_char/modules/home/infra/model/rick_and_morty_characters.dart'
    as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEpisode_1 extends _i1.SmartFake implements _i3.Episode {
  _FakeEpisode_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RickAndMortyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRickAndMortyRepository extends _i1.Mock
    implements _i4.RickAndMortyRepository {
  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.EpisodeEntity>> getEpisode(
          String? episodeNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEpisode,
          [episodeNumber],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, _i7.EpisodeEntity>>.value(
                _FakeEither_0<_i6.Failure, _i7.EpisodeEntity>(
          this,
          Invocation.method(
            #getEpisode,
            [episodeNumber],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.Either<_i6.Failure, _i7.EpisodeEntity>>.value(
                _FakeEither_0<_i6.Failure, _i7.EpisodeEntity>(
          this,
          Invocation.method(
            #getEpisode,
            [episodeNumber],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i7.EpisodeEntity>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i8.CharacterEntity>>> getCharacters(
    int? episodeId,
    List<String>? characterUrls,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharacters,
          [
            episodeId,
            characterUrls,
          ],
        ),
        returnValue: _i5
            .Future<_i2.Either<_i6.Failure, List<_i8.CharacterEntity>>>.value(
            _FakeEither_0<_i6.Failure, List<_i8.CharacterEntity>>(
          this,
          Invocation.method(
            #getCharacters,
            [
              episodeId,
              characterUrls,
            ],
          ),
        )),
        returnValueForMissingStub: _i5
            .Future<_i2.Either<_i6.Failure, List<_i8.CharacterEntity>>>.value(
            _FakeEither_0<_i6.Failure, List<_i8.CharacterEntity>>(
          this,
          Invocation.method(
            #getCharacters,
            [
              episodeId,
              characterUrls,
            ],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, List<_i8.CharacterEntity>>>);
}

/// A class which mocks [LoadEpisodeUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadEpisodeUsecase extends _i1.Mock
    implements _i9.LoadEpisodeUsecase {
  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.EpisodeEntity>> call(
          String? episodeNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [episodeNumber],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, _i7.EpisodeEntity>>.value(
                _FakeEither_0<_i6.Failure, _i7.EpisodeEntity>(
          this,
          Invocation.method(
            #call,
            [episodeNumber],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.Either<_i6.Failure, _i7.EpisodeEntity>>.value(
                _FakeEither_0<_i6.Failure, _i7.EpisodeEntity>(
          this,
          Invocation.method(
            #call,
            [episodeNumber],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i7.EpisodeEntity>>);
}

/// A class which mocks [LoadCharactersUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadCharactersUsecase extends _i1.Mock
    implements _i10.LoadCharactersUsecase {
  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i8.CharacterEntity>>> call(
    int? episodeId,
    List<String>? characterUrls,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            episodeId,
            characterUrls,
          ],
        ),
        returnValue: _i5
            .Future<_i2.Either<_i6.Failure, List<_i8.CharacterEntity>>>.value(
            _FakeEither_0<_i6.Failure, List<_i8.CharacterEntity>>(
          this,
          Invocation.method(
            #call,
            [
              episodeId,
              characterUrls,
            ],
          ),
        )),
        returnValueForMissingStub: _i5
            .Future<_i2.Either<_i6.Failure, List<_i8.CharacterEntity>>>.value(
            _FakeEither_0<_i6.Failure, List<_i8.CharacterEntity>>(
          this,
          Invocation.method(
            #call,
            [
              episodeId,
              characterUrls,
            ],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, List<_i8.CharacterEntity>>>);
}

/// A class which mocks [RemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDatasource extends _i1.Mock implements _i11.RemoteDatasource {
  @override
  _i5.Future<_i3.Episode> fetchEpisode(String? episodeNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchEpisode,
          [episodeNumber],
        ),
        returnValue: _i5.Future<_i3.Episode>.value(_FakeEpisode_1(
          this,
          Invocation.method(
            #fetchEpisode,
            [episodeNumber],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.Episode>.value(_FakeEpisode_1(
          this,
          Invocation.method(
            #fetchEpisode,
            [episodeNumber],
          ),
        )),
      ) as _i5.Future<_i3.Episode>);

  @override
  _i5.Future<List<_i12.RickAndMortyCharacter>> fetchCharacters(
          List<int>? characterIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchCharacters,
          [characterIds],
        ),
        returnValue: _i5.Future<List<_i12.RickAndMortyCharacter>>.value(
            <_i12.RickAndMortyCharacter>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i12.RickAndMortyCharacter>>.value(
                <_i12.RickAndMortyCharacter>[]),
      ) as _i5.Future<List<_i12.RickAndMortyCharacter>>);
}

/// A class which mocks [LocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDatasource extends _i1.Mock implements _i13.LocalDatasource {
  @override
  _i5.Future<void> insertEpisode(_i3.Episode? episode) => (super.noSuchMethod(
        Invocation.method(
          #insertEpisode,
          [episode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.Episode?> getEpisode(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getEpisode,
          [id],
        ),
        returnValue: _i5.Future<_i3.Episode?>.value(),
        returnValueForMissingStub: _i5.Future<_i3.Episode?>.value(),
      ) as _i5.Future<_i3.Episode?>);

  @override
  _i5.Future<void> saveCharacters(
    List<_i12.RickAndMortyCharacter>? characters,
    int? episodeId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCharacters,
          [
            characters,
            episodeId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i12.RickAndMortyCharacter>> getCharactersByEpisode(
          int? episodeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharactersByEpisode,
          [episodeId],
        ),
        returnValue: _i5.Future<List<_i12.RickAndMortyCharacter>>.value(
            <_i12.RickAndMortyCharacter>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i12.RickAndMortyCharacter>>.value(
                <_i12.RickAndMortyCharacter>[]),
      ) as _i5.Future<List<_i12.RickAndMortyCharacter>>);
}
